name: Generate snake animation

on:
  schedule: # execute every 12 hours
    - cron: "*/12 * * * *"

  workflow_dispatch:

  push:
    branches:
    - master

jobs:
  generate:
    permissions:
      contents: write
    runs-on: windows-latest
    timeout-minutes: 5

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Generate snake.svg
        uses: Platane/snk@v3
        with:
          github_user_name: bijayrauniyar0
          output_file: dist/snake.svg
          palette: github-dark

      - name: Push snake.svg to the output branch
        uses: ad-m/github-push-action@master
        with:
          branch: output
          directory: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
